"""calendar_id as bigint

Revision ID: 030d85805162
Revises: 69e440057b76
Create Date: 2026-08-22 16:57:30.482591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030d85805162'
down_revision = '69e440057b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_day_pairs', 'calendar_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='calendar')
    op.alter_column('calendars', 'calendar_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=False,
               schema='calendar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'calendar_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False,
               schema='calendar')
    op.alter_column('calendar_day_pairs', 'calendar_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='calendar')
    # ### end Alembic commands ###
