"""add seq column to cluster_profiles

Revision ID: 1968caf074da
Revises: c4be84f2e2b2
Create Date: 2026-08-23 18:14:29.733414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1968caf074da'
down_revision = 'c4be84f2e2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_profiles', sa.Column('seq', sa.Integer(), nullable=False, server_default='0'), schema='calendar')
    # ### end Alembic commands ###
    # Backfill: the server_default lands every existing row on seq=0, and an
    # all-ties column makes `ORDER BY seq` non-deterministic in Postgres — strictly
    # worse than the alphabetical ordering seq replaces. Seed seq from the previous
    # (name) ordering so a fresh deploy starts out matching the old behaviour and
    # every row gets a distinct rank the drag-reorder UI can then rewrite.
    op.execute(
        "UPDATE calendar.cluster_profiles SET seq = sub.rn "
        "FROM (SELECT id, row_number() OVER (ORDER BY name) - 1 AS rn "
        "FROM calendar.cluster_profiles) sub "
        "WHERE calendar.cluster_profiles.id = sub.id"
    )
    op.alter_column('cluster_profiles', 'seq', server_default=None, schema='calendar')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_profiles', 'seq', schema='calendar')
    # ### end Alembic commands ###
