"""add seq column to cluster_profiles

Revision ID: 1968caf074da
Revises: c4be84f2e2b2
Create Date: 2026-08-23 18:14:29.733414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1968caf074da'
down_revision = 'c4be84f2e2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_profiles', sa.Column('seq', sa.Integer(), nullable=False, server_default='0'), schema='calendar')
    # ### end Alembic commands ###
    op.alter_column('cluster_profiles', 'seq', server_default=None, schema='calendar')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_profiles', 'seq', schema='calendar')
    # ### end Alembic commands ###
