"""add erp_cluster_type to stores

Revision ID: 641c7b61a76a
Revises: d4bcc45565ed
Create Date: 2026-08-22 16:43:18.283750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641c7b61a76a'
down_revision = 'd4bcc45565ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('erp_cluster_type', sa.String(), nullable=True), schema='masterdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'erp_cluster_type', schema='masterdata')
    # ### end Alembic commands ###
