"""add real per-cluster calendar tables

Revision ID: 69e440057b76
Revises: 641c7b61a76a
Create Date: 2026-08-22 16:56:11.643401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e440057b76'
down_revision = '641c7b61a76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('calendar_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref_year', sa.Integer(), nullable=False),
    sa.Column('fut_year', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('calendar_id'),
    schema='calendar'
    )
    op.create_table('store_calendar_clusters',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    schema='calendar'
    )
    op.create_table('calendar_day_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('fut_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendars.calendar_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'cluster_name', 'seq', name='uq_calendar_day_pairs_identity'),
    schema='calendar'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_day_pairs', schema='calendar')
    op.drop_table('store_calendar_clusters', schema='calendar')
    op.drop_table('calendars', schema='calendar')
    # ### end Alembic commands ###
