"""input_values identity columns not null (fix ON CONFLICT dedup bug)

Revision ID: 92623caf6e07
Revises: 030d85805162
Create Date: 2026-08-22 20:13:21.063603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92623caf6e07'
down_revision = '030d85805162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_values', 'store_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='planning_inputs')
    op.alter_column('input_values', 'division_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='planning_inputs')
    op.alter_column('input_values', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='planning_inputs')
    op.alter_column('input_values', 'row_key',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='planning_inputs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_values', 'row_key',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='planning_inputs')
    op.alter_column('input_values', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='planning_inputs')
    op.alter_column('input_values', 'division_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='planning_inputs')
    op.alter_column('input_values', 'store_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='planning_inputs')
    # ### end Alembic commands ###
