"""add extra_dims and metric to salesdata_link_selection

Revision ID: a9b6a4b4d35f
Revises: deb71d84d127
Create Date: 2026-08-27 14:35:08.836782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b6a4b4d35f'
down_revision = 'deb71d84d127'
branch_labels = None
depends_on = None


def upgrade():
    # server_default so existing rows (already-synced mw/dw selections) get a
    # valid value instead of failing the NOT NULL add outright.
    op.add_column('salesdata_link_selection', sa.Column('extra_dims', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'), schema='calendar')
    op.add_column('salesdata_link_selection', sa.Column('metric', sa.String(), nullable=True), schema='calendar')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesdata_link_selection', 'metric', schema='calendar')
    op.drop_column('salesdata_link_selection', 'extra_dims', schema='calendar')
    # ### end Alembic commands ###
