"""add calendar engine tables

Revision ID: c4be84f2e2b2
Revises: d6bf4d3937d9
Create Date: 2026-08-23 10:50:17.842819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4be84f2e2b2'
down_revision = 'd6bf4d3937d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state_meta',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('active_cluster_idx', sa.Integer(), nullable=False),
    sa.Column('ref_year', sa.String(), nullable=True),
    sa.Column('fut_year', sa.String(), nullable=True),
    sa.Column('max_shift', sa.String(), nullable=True),
    sa.Column('mo_pri', sa.String(), nullable=True),
    sa.Column('theme_id', sa.String(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('migrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_app_state_meta_singleton'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_table('cluster_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_cluster_profiles_name'),
    schema='calendar'
    )
    op.create_table('festival_changelog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('range_key', sa.String(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('festival_name', sa.String(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('fut_date', sa.Date(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('range_key', 'cluster_name', 'festival_name', name='uq_festival_changelog_identity'),
    schema='calendar'
    )
    op.create_table('salesdata_link_selection',
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('months', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('mw', 'dw')", name='ck_salesdata_link_selection_source_type'),
    sa.PrimaryKeyConstraint('source_type'),
    schema='calendar'
    )
    op.create_table('store_cluster_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('reassigned', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_table('store_cluster_map_meta',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_store_cluster_map_meta_singleton'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_table('calendar_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.calendars.calendar_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'cluster_name', name='uq_calendar_clusters_identity'),
    schema='calendar'
    )
    op.create_table('cluster_profile_festivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_profile_id', sa.Integer(), nullable=False),
    sa.Column('source_festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('fut_date', sa.Date(), nullable=False),
    sa.Column('pre', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_profile_id'], ['calendar.cluster_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_table('calendar_cluster_festivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_cluster_id', sa.Integer(), nullable=False),
    sa.Column('source_festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('fut_date', sa.Date(), nullable=False),
    sa.Column('pre', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_cluster_id'], ['calendar.calendar_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_cluster_festivals', schema='calendar')
    op.drop_table('cluster_profile_festivals', schema='calendar')
    op.drop_table('calendar_clusters', schema='calendar')
    op.drop_table('store_cluster_map_meta', schema='calendar')
    op.drop_table('store_cluster_log', schema='calendar')
    op.drop_table('salesdata_link_selection', schema='calendar')
    op.drop_table('festival_changelog', schema='calendar')
    op.drop_table('cluster_profiles', schema='calendar')
    op.drop_table('app_state_meta', schema='calendar')
    # ### end Alembic commands ###
