"""initial schema: masterdata calendar planning_inputs sync engine

Revision ID: d4bcc45565ed
Revises: 
Create Date: 2026-08-22 16:28:25.690983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bcc45565ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_shift_map',
    sa.Column('current_date', sa.Date(), nullable=False),
    sa.Column('ly_mapped_date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('current_date'),
    schema='calendar'
    )
    op.create_table('forecast_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('palette', sa.String(), nullable=True),
    sa.Column('growth_overrides', sa.JSON(), nullable=True),
    sa.Column('overall_override', sa.JSON(), nullable=True),
    sa.Column('input_snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    schema='engine'
    )
    op.create_table('clusters',
    sa.Column('cluster_key', sa.String(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_key'),
    schema='masterdata'
    )
    op.create_table('divisions',
    sa.Column('division_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('division_code'),
    schema='masterdata'
    )
    op.create_table('nso_openings',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('opening_month', sa.Date(), nullable=False),
    sa.Column('is_named', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    schema='masterdata'
    )
    op.create_table('input_values_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_value_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Numeric(), nullable=True),
    sa.Column('new_value', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='planning_inputs'
    )
    op.create_index(op.f('ix_planning_inputs_input_values_history_input_value_id'), 'input_values_history', ['input_value_id'], unique=False, schema='planning_inputs')
    op.create_table('lever_definitions',
    sa.Column('lever_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('lever_key'),
    schema='planning_inputs'
    )
    op.create_table('periods',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('period_id'),
    sa.UniqueConstraint('label'),
    schema='planning_inputs'
    )
    op.create_table('sources',
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ttl_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_key'),
    schema='sync'
    )
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('division_code', sa.String(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['division_code'], ['masterdata.divisions.division_code'], ),
    sa.ForeignKeyConstraint(['period_id'], ['planning_inputs.periods.period_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['engine.forecast_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='engine'
    )
    op.create_table('departments',
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('division_code', sa.String(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['masterdata.divisions.division_code'], ),
    sa.PrimaryKeyConstraint('department_name'),
    schema='masterdata'
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('ref_store', sa.String(), nullable=True),
    sa.Column('cluster_key', sa.String(), nullable=True),
    sa.Column('store_status', sa.String(), nullable=True),
    sa.Column('store_current_status', sa.String(), nullable=True),
    sa.Column('store_grade', sa.String(), nullable=True),
    sa.Column('gm_grade', sa.String(), nullable=True),
    sa.Column('festival_grouping', sa.String(), nullable=True),
    sa.Column('region_type', sa.String(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_key'], ['masterdata.clusters.cluster_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'valid_from', name='uq_stores_store_id_valid_from'),
    schema='masterdata'
    )
    op.create_index(op.f('ix_masterdata_stores_store_id'), 'stores', ['store_id'], unique=False, schema='masterdata')
    op.create_table('input_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lever_key', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('division_code', sa.String(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('row_key', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['masterdata.divisions.division_code'], ),
    sa.ForeignKeyConstraint(['lever_key'], ['planning_inputs.lever_definitions.lever_key'], ),
    sa.ForeignKeyConstraint(['period_id'], ['planning_inputs.periods.period_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lever_key', 'store_id', 'division_code', 'period_id', 'row_key', name='uq_input_values_identity'),
    schema='planning_inputs'
    )
    op.create_table('sync_runs',
    sa.Column('sync_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_added', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_key'], ['sync.sources.source_key'], ),
    sa.PrimaryKeyConstraint('sync_run_id'),
    schema='sync'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs', schema='sync')
    op.drop_table('input_values', schema='planning_inputs')
    op.drop_index(op.f('ix_masterdata_stores_store_id'), table_name='stores', schema='masterdata')
    op.drop_table('stores', schema='masterdata')
    op.drop_table('departments', schema='masterdata')
    op.drop_table('forecast_results', schema='engine')
    op.drop_table('sources', schema='sync')
    op.drop_table('periods', schema='planning_inputs')
    op.drop_table('lever_definitions', schema='planning_inputs')
    op.drop_index(op.f('ix_planning_inputs_input_values_history_input_value_id'), table_name='input_values_history', schema='planning_inputs')
    op.drop_table('input_values_history', schema='planning_inputs')
    op.drop_table('nso_openings', schema='masterdata')
    op.drop_table('divisions', schema='masterdata')
    op.drop_table('clusters', schema='masterdata')
    op.drop_table('forecast_runs', schema='engine')
    op.drop_table('day_shift_map', schema='calendar')
    # ### end Alembic commands ###
