"""add auth workflow audit schemas

Revision ID: d6bf4d3937d9
Revises: 92623caf6e07
Create Date: 2026-08-22 22:54:33.958745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bf4d3937d9'
down_revision = '92623caf6e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('plan_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_run_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['current_run_id'], ['engine.forecast_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('data_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_key', sa.JSON(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('plan_cycle_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['workflow.plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('plan_cycle_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_cycle_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['workflow.plan_cycles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['engine.forecast_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_cycle_transitions', schema='workflow')
    op.drop_table('data_changes', schema='audit')
    op.drop_table('plan_cycles', schema='workflow')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
