"""add email to users

Revision ID: deb71d84d127
Revises: f2b3c4d5e6a7
Create Date: 2026-08-27 14:02:29.961366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb71d84d127'
down_revision = 'f2b3c4d5e6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email', schema='auth')
    # ### end Alembic commands ###
